"use client";
import {FormEvent,useEffect,useState} from "react";import {createClient} from "@/lib/supabase/client";import {Announcement} from "@/lib/types";
const blank={title_de:"",content_de:"",title_en:"",content_en:"",publish_date:new Date().toISOString().slice(0,10),expires_at:"",important:false,published:false};
export default function Admin(){const supabase=createClient();const[user,setUser]=useState(false),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[items,setItems]=useState<Announcement[]>([]),[form,setForm]=useState(blank),[editing,setEditing]=useState<string|null>(null),[message,setMessage]=useState("");
useEffect(()=>{if(!supabase)return;supabase.auth.getUser().then(({data})=>{setUser(!!data.user);if(data.user)load()})},[]);
async function load(){if(!supabase)return;const{data}=await supabase.from("announcements").select("*").order("created_at",{ascending:false});setItems((data??[])as Announcement[])}
async function login(e:FormEvent){e.preventDefault();if(!supabase)return;const{error}=await supabase.auth.signInWithPassword({email,password});if(error)setMessage("Anmeldung fehlgeschlagen. Bitte Zugangsdaten prüfen.");else{setUser(true);setMessage("");load()}}
async function save(e:FormEvent){e.preventDefault();if(!supabase)return;const payload={...form,expires_at:form.expires_at?new Date(form.expires_at).toISOString():null};const result=editing?await supabase.from("announcements").update(payload).eq("id",editing):await supabase.from("announcements").insert(payload);if(result.error)setMessage(result.error.message);else{setForm(blank);setEditing(null);setMessage("Mitteilung gespeichert.");load()}}
function edit(a:Announcement){setEditing(a.id);setForm({title_de:a.title_de,content_de:a.content_de,title_en:a.title_en??"",content_en:a.content_en??"",publish_date:a.publish_date??"",expires_at:a.expires_at?a.expires_at.slice(0,16):"",important:a.important,published:a.published});window.scrollTo({top:0,behavior:"smooth"})}
async function toggle(a:Announcement){if(!supabase)return;await supabase.from("announcements").update({published:!a.published}).eq("id",a.id);load()}
async function remove(id:string){if(!supabase||!confirm("Mitteilung wirklich löschen?"))return;await supabase.from("announcements").delete().eq("id",id);load()}
if(!supabase)return <main className="admin-shell"><div className="admin-card"><h1>Admin einrichten</h1><p>Bitte Supabase-URL und Anon-Key in <code>.env.local</code> hinterlegen. Die benötigten Variablen stehen in <code>.env.example</code>.</p></div></main>;
if(!user)return <main className="admin-shell"><form className="admin-card" onSubmit={login}><span className="eyebrow">Geschützter Bereich</span><h1>Anmelden</h1><p>Dieser Zugang ist ausschließlich für die Website-Administration.</p><label className="field">E-Mail<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label className="field">Passwort<input type="password" required value={password} onChange={e=>setPassword(e.target.value)}/></label>{message&&<p>{message}</p>}<button className="button">Anmelden →</button></form></main>;
return <main className="admin-shell"><div className="container"><div className="admin-toolbar"><div><span className="eyebrow">Administration</span><h1>Aktuelles verwalten</h1></div><button className="small-button" onClick={async()=>{await supabase.auth.signOut();setUser(false)}}>Abmelden</button></div><form className="admin-card" onSubmit={save}><h2>{editing?"Mitteilung bearbeiten":"Neue Mitteilung"}</h2><label className="field">Titel (Deutsch)<input required value={form.title_de} onChange={e=>setForm({...form,title_de:e.target.value})}/></label><label className="field">Nachricht (Deutsch)<textarea required value={form.content_de} onChange={e=>setForm({...form,content_de:e.target.value})}/></label><label className="field">Title (English)<input value={form.title_en} onChange={e=>setForm({...form,title_en:e.target.value})}/></label><label className="field">Message (English)<textarea value={form.content_en} onChange={e=>setForm({...form,content_en:e.target.value})}/></label><label className="field">Veröffentlichungsdatum<input type="date" value={form.publish_date} onChange={e=>setForm({...form,publish_date:e.target.value})}/></label><label className="field">Ablaufdatum (optional)<input type="datetime-local" value={form.expires_at} onChange={e=>setForm({...form,expires_at:e.target.value})}/></label><label><input type="checkbox" checked={form.important} onChange={e=>setForm({...form,important:e.target.checked})}/> Wichtige Mitteilung</label><br/><label><input type="checkbox" checked={form.published} onChange={e=>setForm({...form,published:e.target.checked})}/> Veröffentlicht</label><div className="admin-actions" style={{marginTop:25}}><button className="button">Speichern →</button>{editing&&<button type="button" className="small-button" onClick={()=>{setEditing(null);setForm(blank)}}>Abbrechen</button>}</div>{message&&<p>{message}</p>}</form><section style={{marginTop:60}}>{items.map(a=><article className="admin-item" key={a.id}><span className="eyebrow">{a.published?"Veröffentlicht":"Entwurf"}{a.important?" · Wichtig":""}</span><h3>{a.title_de}</h3><p>{a.content_de}</p><div className="admin-actions"><button className="small-button" onClick={()=>edit(a)}>Bearbeiten</button><button className="small-button" onClick={()=>toggle(a)}>{a.published?"Ausblenden":"Veröffentlichen"}</button><button className="small-button danger" onClick={()=>remove(a.id)}>Löschen</button></div></article>)}</section></div></main>}
