"use client";
import Image from "next/image"; import Link from "next/link";
import { siteConfig } from "@/lib/config"; import { useLanguage } from "./LanguageProvider";

const copy={
de:{kicker:"Hebamme Simone Eschweiler",title:"Begleitung mit Erfahrung, Ruhe und Vertrauen.",sub:"Für Schwangerschaft, Wochenbett und besondere Lebensphasen.",hero:"Mit fachlicher Kompetenz, traumasensibler Haltung und einem offenen Blick für das, was wirklich gebraucht wird.",cta:"Betreuung anfragen",welcome:"Willkommen",intro:"Jede Schwangerschaft ist einzigartig. Und jede Frau bringt ihre eigene Geschichte, ihre Fragen und ihr eigenes Tempo mit.",welcomeText:"Ich begleite Frauen und Familien mit Ruhe, Erfahrung und Feingefühl durch Schwangerschaft, Wochenbett und Zeiten des Wandels. Dabei geht es nicht nur um Versorgung – sondern darum, Sicherheit zu vermitteln, Vertrauen zu stärken und individuelle Lösungen entstehen zu lassen.",services:"Leistungen",serviceIntro:"Persönliche und fachlich fundierte Begleitung – aufmerksam für Ihre Fragen und das, was Sie gerade brauchen.",learn:"Mehr erfahren",trauma:"Traumasensible Begleitung",traumaSub:"Ein geschützter Raum für Stabilisierung, Orientierung und neue innere Sicherheit.",traumaText:"Traumasensible und neurosystemische Begleitung in besonderen Lebensphasen – ruhig, zugewandt und in Ihrem eigenen Tempo.",about:"Über mich",aboutTitle:"Mit Erfahrung begleiten",aboutText:"Hebamme zu sein bedeutet für mich weit mehr als medizinische Betreuung. Seit vielen Jahren begleite ich Frauen und Familien durch Schwangerschaft, Geburt und Wochenbett – mit Fachwissen, Intuition und einem tiefen Vertrauen in die individuellen Prozesse des Lebens. Mein Anliegen ist es, Frauen zu stärken, Sicherheit zu vermitteln und Räume zu schaffen, in denen Entwicklung möglich wird.",news:"Aktuelles",newsSub:"Hinweise zu Verfügbarkeit, Urlaub und neuen Angeboten.",allNews:"Alle Mitteilungen",online:"Ergänzende Begleitung & Onlineangebote",onlineText:"Neben meiner Hebammentätigkeit entsteht ein ergänzendes Onlineangebot mit Fokus auf ganzheitliche, traumasensible und neurosystemische Begleitung. Dieses Angebot ist unabhängig von den Leistungen der Hebammenversorgung und wird gesondert vergütet.",contact:"Kontakt",contactTitle:"Ich freue mich auf Ihre Anfrage.",contactText:"Für Betreuungsanfragen und weitere Informationen kontaktieren Sie mich bitte per E-Mail.",email:"E-Mail schreiben"},
en:{kicker:"Midwife Simone Eschweiler",title:"Support built on experience, calm and trust.",sub:"For pregnancy, postpartum care and important phases of life.",hero:"With professional expertise, a trauma-sensitive approach and an open perspective on what is truly needed.",cta:"Enquire about care",welcome:"Welcome",intro:"Every pregnancy is unique. And every woman brings her own story, her questions and her own pace.",welcomeText:"I support women and families with calm, experience and sensitivity through pregnancy, the postpartum period and times of change. My work is about more than care – it is about creating safety, strengthening trust and making space for individual solutions.",services:"Services",serviceIntro:"Personal, professionally grounded support – attentive to your questions and to what you need right now.",learn:"Learn more",trauma:"Trauma-sensitive support",traumaSub:"A protected space for stabilisation, orientation and a renewed sense of inner safety.",traumaText:"Trauma-sensitive and neuro-systemic support during significant phases of life – calm, attentive and at your own pace.",about:"About me",aboutTitle:"Support shaped by experience",aboutText:"Being a midwife means far more to me than providing medical care. For many years, I have accompanied women and families through pregnancy, birth and the postpartum period – with expertise, intuition and a deep trust in each person’s individual process. I aim to strengthen women, create a sense of safety and offer spaces in which development can unfold.",news:"Updates",newsSub:"Information about availability, holidays and new services.",allNews:"All updates",online:"Additional support & online services",onlineText:"Alongside my midwifery work, I am developing additional online services focused on holistic, trauma-sensitive and neuro-systemic support. These services are separate from statutory midwifery care and are charged independently.",contact:"Contact",contactTitle:"I look forward to hearing from you.",contactText:"For care enquiries and further information, please contact me by email.",email:"Send an email"}}
const services={de:["Mutterschaftsvorsorge","Hilfe bei Schwangerschaftsbeschwerden","Wochenbettbetreuung","Traumasensible Begleitung"],en:["Maternity care","Support with pregnancy discomfort","Postpartum care","Trauma-sensitive support"]};
const descriptions={de:["Ein geschützter Raum für medizinische Vorsorge, persönliche Fragen und individuelle Begleitung.","Beschwerden in der Schwangerschaft dürfen ernst genommen werden. Gemeinsam schauen wir, was Entlastung schaffen kann.","Einfühlsame Begleitung bei körperlicher Heilung, Stillen, Versorgung des Babys und dem Ankommen als Familie.","Traumasensible und neurosystemische Begleitung in besonderen Lebensphasen."],en:["A protected space for medical check-ups, personal questions and individual support.","Pregnancy discomfort deserves to be taken seriously. Together, we explore what can bring relief.","Sensitive support with physical recovery, feeding, caring for your baby and settling in as a family.","Trauma-sensitive and neuro-systemic support during significant phases of life."]};
export default function HomeContent(){const {locale}=useLanguage(),c=copy[locale];return <main>
<section className="hero"><div className="hero-copy"><div className="hero-inner"><span className="eyebrow">{c.kicker}</span><h1>{c.title}</h1><p className="lead">{c.sub}</p><p>{c.hero}</p><a className="button" href={`mailto:${siteConfig.email}`}>{c.cta} <span>→</span></a></div></div><div className="hero-image"><Image src="/images/detail1.jpeg" alt="Traditionelles Hebammeninstrument auf warmem Holz" fill sizes="(max-width: 980px) 100vw, 48vw" priority /></div></section>
<section className="section welcome"><div className="narrow"><span className="eyebrow">{c.welcome}</span><p className="intro">{c.intro}</p><p>{c.welcomeText}</p></div></section>
<section className="section services"><div className="container"><div className="section-head"><div><span className="eyebrow">01</span><h2>{c.services}</h2></div><p>{c.serviceIntro}</p></div><div className="service-grid">{services[locale].map((s,i)=><article className="service" key={s}><span className="number">0{i+1}</span><h3>{s}</h3><p>{descriptions[locale][i]}</p><Link className="text-link" href={i===3?"/traumasensible-begleitung":"/leistungen"}>{c.learn} →</Link></article>)}</div></div></section>
<section className="section home-story"><div className="container split"><Image className="natural-image" src="/images/detail3.jpeg" alt={locale==="de"?"Traditionelle Hebammentasche":"Traditional midwife bag"} width={1600} height={1066}/><div><span className="eyebrow">{locale==="de"?"Persönlich begleitet":"Personal support"}</span><h2>{locale==="de"?"Fachwissen und Erfahrung – mit Blick für das Wesentliche.":"Knowledge and experience – focused on what matters."}</h2><p>{locale==="de"?"Jede Begleitung orientiert sich an Ihrer individuellen Situation, Ihren Fragen und dem, was Ihnen Sicherheit gibt.":"Every form of support is shaped by your individual situation, your questions and what helps you feel safe."}</p><Link className="text-link" href="/leistungen">{c.learn} →</Link></div></div></section>
<section className="section trauma"><div className="container split"><Image className="split-image" src="/images/detail4.jpeg" alt="Offene Hände als Geste der Begleitung" width={1263} height={1600}/><div className="copy"><span className="eyebrow">{c.trauma}</span><h2>{c.traumaSub}</h2><p>{c.traumaText}</p><Link className="button" href="/traumasensible-begleitung">{c.learn} →</Link></div></div></section>
<section className="section about"><div className="container split"><div><span className="eyebrow">{c.about}</span><h2>{c.aboutTitle}</h2><p>{c.aboutText}</p><Link className="text-link" href="/ueber-mich">{c.learn} →</Link></div><Image className="split-image" src="/images/profile.jpeg" alt="Portrait von Simone Eschweiler" width={986} height={1600}/></div></section>
<section className="section online"><div className="container split"><div><span className="eyebrow">{locale==="de"?"Onlineangebote":"Online services"}</span><h2>{c.online}</h2><p>{c.onlineText}</p><a className="button" href={siteConfig.meloneGrooveUrl} target="_blank" rel="noreferrer">{c.learn} ↗</a></div><Image className="natural-image" src="/images/detail2.jpeg" alt={locale==="de"?"Sei guter Hoffnung":"Be of good hope"} width={1600} height={1066}/></div></section>
<section className="section contact"><div className="narrow"><span className="eyebrow">{c.contact}</span><h2>{c.contactTitle}</h2><p>{c.contactText}</p><a className="button" href={`mailto:${siteConfig.email}`}>{c.email} →</a></div></section>
</main>}
