"use client";
import { useLanguage } from "./LanguageProvider"; import { siteConfig } from "@/lib/config"; import PageHero from "./PageHero";

const content={
de:{eye:"Leistungen",title:"Begleitung rund um Schwangerschaft und Wochenbett",intro:"Fachliche Kompetenz und persönliche Begleitung greifen ineinander – ruhig, achtsam und auf Augenhöhe.",items:[
{t:"Mutterschaftsvorsorge",p:["Die Vorsorge folgt den Mutterschaftsrichtlinien und bietet zugleich Raum für Ihre persönliche Situation.","Medizinische Fragen, Veränderungen und Unsicherheiten dürfen ebenso ihren Platz haben wie das, was Sie gerade beschäftigt.","Ich begleite Sie fachlich fundiert, zugewandt und in Ihrem eigenen Tempo.","Die Vorsorge ist dabei eine Leistung der gesetzlichen Krankenkasse."]},
{t:"Hilfe bei Schwangerschaftsbeschwerden",p:["Beschwerden in der Schwangerschaft dürfen ernst genommen werden und bieten Raum genauer hinzuschauen. Dabei können körperliche Veränderungen, persönliche Fragen und Unsicherheiten ebenso ihren Platz haben wie die Suche nach Möglichkeiten, die im Alltag Entlastung schaffen.","Ich begleite Sie fachlich fundiert, zugewandt und mit Blick auf Ihre individuelle Situation. Wenn eine weitere medizinische Abklärung sinnvoll ist, wird auch dies gemeinsam besprochen.","Die Kosten für die Hebammenhilfe werden dabei von Ihrer gesetzlichen Krankenkasse übernommen."]},
{t:"Wochenbettbetreuung",p:["Einfühlsame Begleitung beim körperlichen Ankommen nach der Geburt, beim Stillen, bei der Versorgung des Babys und beim Ankommen als Familie."]}],cta:"Betreuung anfragen"},
en:{eye:"Services",title:"Support throughout pregnancy and the postpartum period",intro:"Professional expertise and personal support come together – calmly, attentively and as equals.",items:[
{t:"Maternity care",p:["Maternity care follows the German maternity guidelines while also making space for your personal situation.","Medical questions, changes and uncertainties are welcome, as is anything else that may be on your mind.","I support you with professional expertise, attentiveness and at your own pace.","Maternity care is covered by statutory health insurance."]},
{t:"Support with pregnancy discomfort",p:["Discomfort during pregnancy deserves to be taken seriously and offers an opportunity to look more closely. Physical changes, personal questions and uncertainties are welcome, as is the search for ways to make everyday life easier.","I support you with professional expertise, attentiveness and consideration for your individual situation. If further medical assessment would be helpful, we will discuss this together.","The costs of this midwifery support are covered by your statutory health insurance."]},
{t:"Postpartum care",p:["Sensitive support as you physically recover after birth, with breastfeeding, caring for your baby and settling in as a family."]}],cta:"Enquire about care"}};

export default function ServicesPage(){const {locale}=useLanguage(),c=content[locale];return <main><PageHero eyebrow={c.eye} title={c.title} text={c.intro}/><section className="section"><div className="container services-detail">{c.items.map(x=><article className="detail-row" key={x.t}><div><h2>{x.t}</h2>{x.p.map(p=><p key={p}>{p}</p>)}</div></article>)}</div></section><section className="section contact"><a className="button" href={`mailto:${siteConfig.email}`}>{c.cta} →</a></section></main>}
